# Generated by Django 3.2.5 on 2021-10-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
