# Generated by Django 3.2.5 on 2021-10-17 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_create_at_diaries_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='history01_display_date',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)]),
        ),
        migrations.AlterField(
            model_name='pages',
            name='history02_display_date',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)]),
        ),
        migrations.AlterField(
            model_name='pages',
            name='history03_display_date',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)]),
        ),
    ]
