# Generated by Django 3.2.5 on 2021-11-22 17:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211018_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='id',
        ),
        migrations.AlterField(
            model_name='diaries',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diaries',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='history01_display_date',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)]),
        ),
        migrations.AlterField(
            model_name='pages',
            name='history02_display_date',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)]),
        ),
        migrations.AlterField(
            model_name='pages',
            name='history03_display_date',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(366)]),
        ),
        migrations.AlterField(
            model_name='pages',
            name='user_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_page', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
