# Generated by Django 3.2.5 on 2021-11-22 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_diaries_user_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaries',
            name='user_diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pages',
            name='user_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_page', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
